import { HttpStatus } from '@nestjs/common';
import { CommentVisibility, TaskLinkEntityType, TaskStatus, type Prisma } from '@prisma/client';
import type { AuditService } from '../../core/audit.service.js';
import { AppException } from '../../core/http-kernel.js';
import type { CommunicationActor, CommunicationGroupsService, MentionTarget, ResolvedMention } from '../communication-groups/communication-groups.service.js';
import type { NotificationsService } from '../notifications/notifications.service.js';
import type { TasksService } from '../tasks/tasks.service.js';
import type { ComplaintCommentRecord, ComplaintsRepository } from './complaints.repository.js';

export type CreateComplaintCommentInput = { complaintId: string; body: string; visibility: CommentVisibility; actorId?: string | null; actorRole?: string | null; actorBranchId?: string | null; actorPermissions?: string[]; mentionTargets?: MentionTarget[]; ccUserIds?: string[]; confirmedRecipientCount?: number; actionTask?: { title: string; assigneeId: string; dueAt: string }; correlationId?: string | null; ipAddress?: string | null; userAgent?: string | null };
export type ComplaintCommentResult = { id: string; complaintId: string; body: string; visibility: CommentVisibility; authorId: string | null; authorName?: string; authorNameAr?: string; mentions?: { userId: string; name: string; nameAr: string; source: string; sourceLabel: string }[]; createdTaskId?: string | null; createdAt: string };
type Deps = { repository: ComplaintsRepository; audit: AuditService; notifications?: NotificationsService | undefined; tasks?: TasksService | undefined; groups?: CommunicationGroupsService | undefined };

export async function createComplaintComment(deps: Deps, input: CreateComplaintCommentInput): Promise<ComplaintCommentResult> {
  const body = nonEmpty(input.body); assertPublicSafe(input);
  const internal = input.visibility === CommentVisibility.INTERNAL;
  const collaboration = Boolean(input.mentionTargets?.length || input.ccUserIds?.length || input.actionTask);
  const complaint = internal && collaboration ? await requiredComplaint(deps.repository, input.complaintId) : null;
  const actor = internal && collaboration ? requiredActor(input) : null;
  if (internal && collaboration && !deps.groups) throw forbidden();
  const mentions = internal && deps.groups && actor && complaint ? await deps.groups.resolveMentions(actor, complaint.branchId, input.mentionTargets ?? []) : [];
  const cc = internal && deps.groups && actor && complaint ? await resolveCc(deps.groups, actor, complaint.branchId, input.ccUserIds ?? []) : [];
  deps.groups?.assertAudience(new Set([...mentions.map((item) => item.userId), ...cc.map((item) => item.userId)]).size, input.confirmedRecipientCount);
  const assignment = input.actionTask && deps.groups && actor && complaint ? await actionAssignee(deps.groups, actor, complaint.branchId, input.actionTask.assigneeId) : null;
  const committed = await deps.repository.transaction(async (client) => {
    for (const recipient of cc) await deps.repository.addWatcher(input.complaintId, recipient.userId, actor!.userId, client);
    const comment = await deps.repository.createComment({ complaintId: input.complaintId, authorId: input.actorId ?? null, body, visibility: input.visibility, ...(mentions.length ? { mentions: mentions.map(mentionData) } : {}) }, client);
    const task = input.actionTask ? await createActionTask(deps.tasks, input, input.complaintId, actor!.userId, client) : null;
    await deps.audit.record(commentAudit(input, comment, task?.id ?? null, mentions.length, cc.length), client);
    return { comment, task, mentions };
  });
  if (internal && collaboration && complaint) {
    const watchers = (await deps.repository.listWatchers(complaint.id)).map(({ userId, user }) => ({ userId, email: user.email, nameEn: user.nameEn, nameAr: user.nameAr }));
    await deps.notifications?.queueCollaboration({ recordType: 'COMPLAINT', recordId: complaint.id, complaintId: complaint.id, href: `/complaints/${complaint.id}?tab=communication`, title: complaint.subject, excerpt: committed.comment.body, confidential: false, eventKey: `complaint-comment:${committed.comment.id}`, mentions: committed.mentions, watchers });
    if (committed.task && assignment) await deps.notifications?.queueCollaboration({ recordType: 'TASK', recordId: committed.task.id, complaintId: complaint.id, href: `/tasks/${committed.task.id}`, title: committed.task.title, excerpt: null, confidential: committed.task.confidentialityLevel !== 'NORMAL', eventKey: `task-assigned:${committed.task.id}`, assignment, mentions: [], watchers: [] });
  }
  return commentItem(committed.comment, committed.task?.id ?? null);
}

export async function complaintCommunicationTargets(deps: Deps, complaintId: string, actor: CommunicationActor, query = '') { const complaint = await requiredComplaint(deps.repository, complaintId); if (!deps.groups) throw forbidden(); const targets = await deps.groups.targets(actor, complaint.branchId, query); const watchers = await deps.repository.listWatchers(complaint.id); return { ...targets, currentWatchers: watchers.map(({ userId, user }) => ({ userId, name: user.nameEn, nameAr: user.nameAr })), capabilities: { canComment: true, canManage: true, canManageWatchers: true } }; }
export async function addComplaintWatcher(deps: Deps, complaintId: string, userId: string, actor: CommunicationActor, context: Pick<CreateComplaintCommentInput, 'correlationId' | 'ipAddress' | 'userAgent'> = {}): Promise<void> { const complaint = await requiredComplaint(deps.repository, complaintId); if (!deps.groups) throw forbidden(); if (userId !== actor.userId) await deps.groups.assertRecipient(actor, complaint.branchId, userId); await deps.repository.transaction(async (client) => { await deps.repository.addWatcher(complaint.id, userId, actor.userId, client); await deps.audit.record(watcherAudit('complaint_watcher_added', complaint.id, complaint.branchId, actor.userId, userId, context), client); }); }
export async function removeComplaintWatcher(deps: Deps, complaintId: string, userId: string, actor: CommunicationActor, context: Pick<CreateComplaintCommentInput, 'correlationId' | 'ipAddress' | 'userAgent'> = {}): Promise<void> { const complaint = await requiredComplaint(deps.repository, complaintId); await deps.repository.transaction(async (client) => { await deps.repository.removeWatcher(complaint.id, userId, client); await deps.audit.record(watcherAudit('complaint_watcher_removed', complaint.id, complaint.branchId, actor.userId, userId, context), client); }); }
export async function listComplaintComments(repository: ComplaintsRepository, complaintId: string): Promise<ComplaintCommentResult[]> { return (await repository.listComments(complaintId)).map((comment) => commentItem(comment)); }
export async function listPublicComplaintComments(repository: ComplaintsRepository, complaintId: string): Promise<ComplaintCommentResult[]> { return (await repository.listPublicComments(complaintId)).map(publicCommentItem); }

async function requiredComplaint(repository: ComplaintsRepository, complaintId: string) { const complaint = await repository.findDetail(complaintId); if (!complaint) throw new AppException('COMPLAINT_NOT_FOUND', 'Complaint not found', HttpStatus.NOT_FOUND); return complaint; }
function requiredActor(input: CreateComplaintCommentInput): CommunicationActor { if (!input.actorId || !input.actorRole) throw forbidden(); return { userId: input.actorId, roleCode: input.actorRole, branchId: input.actorBranchId ?? null, permissions: input.actorPermissions ?? [] }; }
function assertPublicSafe(input: CreateComplaintCommentInput): void { if (input.visibility === CommentVisibility.PUBLIC && (input.mentionTargets?.length || input.ccUserIds?.length || input.actionTask || input.confirmedRecipientCount)) throw new AppException('VALIDATION_FAILED', 'Public comments cannot include internal collaboration', HttpStatus.BAD_REQUEST, [{ field: 'visibility', code: 'FORBIDDEN', message: 'Public comments cannot include mentions, CC recipients, or action tasks.' }]); }
function mentionData(item: ResolvedMention) { return { recipientUserId: item.userId, source: item.source, sourceId: item.sourceId, sourceLabel: item.sourceLabel }; }
async function resolveCc(groups: CommunicationGroupsService, actor: CommunicationActor, branchId: string, ids: string[]): Promise<ResolvedMention[]> { const found = new Map<string, ResolvedMention>(); for (const id of ids) { if (id === actor.userId) continue; await groups.assertRecipient(actor, branchId, id); (await groups.resolveMentions(actor, branchId, [{ type: 'USER', id }])).forEach((item) => found.set(item.userId, item)); } return [...found.values()]; }
async function actionAssignee(groups: CommunicationGroupsService, actor: CommunicationActor, branchId: string, userId: string): Promise<ResolvedMention | null> { if (userId === actor.userId) return null; await groups.assertRecipient(actor, branchId, userId); const result = await groups.resolveMentions(actor, branchId, [{ type: 'USER', id: userId }]); const assignee = result.find((item) => item.userId === userId); if (!assignee) throw new AppException('COLLABORATION_TARGET_FORBIDDEN', 'Collaboration target is not available', HttpStatus.FORBIDDEN); return assignee; }
async function createActionTask(tasks: TasksService | undefined, input: CreateComplaintCommentInput, complaintId: string, ownerId: string, client: Prisma.TransactionClient) { if (!input.actionTask || !tasks) throw new AppException('VALIDATION_FAILED', 'Invalid complaint action task', HttpStatus.BAD_REQUEST); return tasks.createInTransaction({ title: input.actionTask.title, ownerId, assigneeId: input.actionTask.assigneeId, dueAt: input.actionTask.dueAt, status: TaskStatus.OPEN, nextAction: { what: input.actionTask.title, whoId: input.actionTask.assigneeId, when: input.actionTask.dueAt }, links: [{ entityType: TaskLinkEntityType.COMPLAINT, entityId: complaintId }] }, input, client); }
function commentItem(comment: ComplaintCommentRecord, createdTaskId: string | null = null): ComplaintCommentResult { return { id: comment.id, complaintId: comment.complaintId, authorId: comment.authorId, ...(comment.author ? { authorName: comment.author.nameEn, authorNameAr: comment.author.nameAr } : {}), body: comment.body, visibility: comment.visibility, ...(comment.mentions?.length ? { mentions: comment.mentions.map((mention) => ({ userId: mention.recipientUserId, name: mention.recipientUser.nameEn, nameAr: mention.recipientUser.nameAr, source: mention.source, sourceLabel: mention.sourceLabel })) } : {}), ...(createdTaskId ? { createdTaskId } : {}), createdAt: comment.createdAt.toISOString() }; }
function publicCommentItem(comment: ComplaintCommentRecord): ComplaintCommentResult { return { id: comment.id, complaintId: comment.complaintId, authorId: comment.authorId, body: comment.body, visibility: comment.visibility, createdAt: comment.createdAt.toISOString() }; }
function commentAudit(input: CreateComplaintCommentInput, comment: ComplaintCommentRecord, createdTaskId: string | null, mentionCount: number, ccCount: number) { return { eventType: 'COMMENT' as const, action: input.visibility === CommentVisibility.PUBLIC ? 'public_comment_created' : 'internal_comment_created', actorId: input.actorId ?? null, branchId: null, targetType: 'complaint_comment', targetId: comment.id, correlationId: input.correlationId ?? null, ipAddress: input.ipAddress ?? null, userAgent: input.userAgent ?? null, metadata: { complaintId: input.complaintId, visibility: input.visibility, ...(createdTaskId || mentionCount || ccCount ? { createdTaskId, mentionCount, ccCount } : {}) } }; }
function watcherAudit(action: string, complaintId: string, branchId: string, actorId: string, userId: string, context: Pick<CreateComplaintCommentInput, 'correlationId' | 'ipAddress' | 'userAgent'>) { return { eventType: 'COMMENT' as const, action, actorId, branchId, targetType: 'complaint', targetId: complaintId, correlationId: context.correlationId ?? null, ipAddress: context.ipAddress ?? null, userAgent: context.userAgent ?? null, metadata: { userId } }; }
function nonEmpty(value: string): string { const text = value.trim(); if (!text) throw new AppException('VALIDATION_FAILED', 'Invalid complaint comment', HttpStatus.BAD_REQUEST, [{ field: 'body', code: 'REQUIRED', message: 'body is required.' }]); return text; }
function forbidden(): AppException { return new AppException('RBAC_FORBIDDEN', 'Forbidden', HttpStatus.FORBIDDEN); }
