export const permissionDefinitions = [
  ['STAFF_LOGIN', 'Log in to staff system', 'تسجيل الدخول إلى نظام الموظفين'],
  ['PORTAL_SUBMIT', 'Submit portal complaint', 'تقديم شكوى عبر البوابة'],
  ['COMPLAINT_CREATE', 'Create internal complaint', 'إنشاء شكوى داخلية'],
  ['COMPLAINT_VIEW_ASSIGNED', 'View assigned complaints', 'عرض الشكاوى المسندة'],
  ['COMPLAINT_VIEW_BRANCH', 'View branch complaints', 'عرض شكاوى الفرع'],
  ['COMPLAINT_VIEW_ALL', 'View all branch complaints', 'عرض شكاوى جميع الفروع'],
  ['COMPLAINT_EDIT', 'Edit complaint facts', 'تعديل بيانات الشكوى'],
  ['COMPLAINT_SUBMIT', 'Submit complaint for review', 'إرسال الشكوى للمراجعة'],
  ['COMPLAINT_APPROVE', 'Approve complaint', 'اعتماد الشكوى'],
  ['COMPLAINT_ASSIGN', 'Assign investigation owner', 'تعيين مالك التحقيق'],
  ['COMPLAINT_COMMENT_INTERNAL', 'Add internal comment', 'إضافة تعليق داخلي'],
  ['COMPLAINT_COMMENT_PUBLIC', 'Add customer update', 'إضافة تحديث للعميل'],
  ['COMPLAINT_RESOLVE', 'Resolve complaint', 'حل الشكوى'],
  ['COMPLAINT_CLOSE', 'Close complaint', 'إغلاق الشكوى'],
  ['COMPLAINT_REOPEN', 'Reopen complaint', 'إعادة فتح الشكوى'],
  ['COMPLAINT_REJECT', 'Reject complaint', 'رفض الشكوى'],
  ['ATTACHMENT_UPLOAD_STAFF', 'Upload staff attachment', 'رفع مرفق الموظف'],
  ['ATTACHMENT_DOWNLOAD', 'Download attachment', 'تنزيل المرفق'],
  ['COMPENSATION_VIEW', 'View compensation metadata', 'عرض بيانات التعويض'],
  ['COMPENSATION_PROPOSE', 'Propose compensation', 'اقتراح تعويض'],
  ['COMPENSATION_APPROVE', 'Approve compensation', 'اعتماد التعويض'],
  ['USERS_MANAGE', 'Manage users', 'إدارة المستخدمين'],
  ['ROLES_MANAGE', 'Manage roles and permissions', 'إدارة الأدوار والصلاحيات'],
  ['MASTER_DATA_MANAGE', 'Manage master data', 'إدارة البيانات المرجعية'],
  ['SLA_MANAGE', 'Manage SLA policy', 'إدارة سياسة اتفاقية مستوى الخدمة'],
  ['NOTIFICATIONS_MANAGE', 'Manage notification templates', 'إدارة قوالب الإشعارات'],
  ['REPORT_VIEW', 'View operational reports', 'عرض التقارير التشغيلية'],
  ['REPORT_EXPORT', 'Export reports', 'تصدير التقارير'],
  ['AUDIT_VIEW', 'View audit log', 'عرض سجل التدقيق'],
  ['AUDIT_EXPORT', 'Export audit log', 'تصدير سجل التدقيق'],
  ['INTEGRATIONS_MANAGE', 'Configure integrations', 'تهيئة التكاملات'],
] as const;

export type PermissionCode = (typeof permissionDefinitions)[number][0];

export const defaultRolePermissions: Record<string, readonly PermissionCode[]> = {
  ADMIN: permissionDefinitions.map(([code]) => code),
  CR_OFFICER: ['STAFF_LOGIN', 'COMPLAINT_CREATE', 'COMPLAINT_VIEW_ASSIGNED', 'COMPLAINT_VIEW_BRANCH', 'COMPLAINT_EDIT', 'COMPLAINT_SUBMIT', 'COMPLAINT_COMMENT_INTERNAL', 'COMPLAINT_COMMENT_PUBLIC', 'ATTACHMENT_UPLOAD_STAFF', 'ATTACHMENT_DOWNLOAD', 'COMPENSATION_PROPOSE', 'REPORT_VIEW'],
  CR_MANAGER: ['STAFF_LOGIN', 'COMPLAINT_CREATE', 'COMPLAINT_VIEW_ASSIGNED', 'COMPLAINT_VIEW_BRANCH', 'COMPLAINT_EDIT', 'COMPLAINT_SUBMIT', 'COMPLAINT_APPROVE', 'COMPLAINT_ASSIGN', 'COMPLAINT_COMMENT_INTERNAL', 'COMPLAINT_COMMENT_PUBLIC', 'COMPLAINT_RESOLVE', 'COMPLAINT_CLOSE', 'COMPLAINT_REOPEN', 'COMPLAINT_REJECT', 'ATTACHMENT_UPLOAD_STAFF', 'ATTACHMENT_DOWNLOAD', 'COMPENSATION_VIEW', 'COMPENSATION_PROPOSE', 'COMPENSATION_APPROVE', 'REPORT_VIEW', 'REPORT_EXPORT'],
  BRANCH_MANAGER: ['STAFF_LOGIN', 'COMPLAINT_VIEW_ASSIGNED', 'COMPLAINT_VIEW_BRANCH', 'COMPLAINT_ASSIGN', 'COMPLAINT_COMMENT_INTERNAL', 'COMPLAINT_COMMENT_PUBLIC', 'COMPLAINT_RESOLVE', 'COMPLAINT_CLOSE', 'COMPLAINT_REOPEN', 'COMPLAINT_REJECT', 'ATTACHMENT_UPLOAD_STAFF', 'ATTACHMENT_DOWNLOAD', 'COMPENSATION_VIEW', 'COMPENSATION_PROPOSE', 'COMPENSATION_APPROVE', 'REPORT_VIEW', 'REPORT_EXPORT'],
  MGMT_READONLY: ['STAFF_LOGIN', 'COMPLAINT_VIEW_BRANCH', 'REPORT_VIEW'],
  CUSTOMER_PORTAL: ['PORTAL_SUBMIT'],
};
