import type { Locale } from './staff-shell';

const en = {
  title: 'Communication groups', personal: 'My groups', shared: 'Shared groups', name: 'Group name', members: 'Members', memberCount: '{count} members', search: 'Search employees', add: 'Add employee', remove: 'Remove', create: 'Create new group', createTitle: 'Create a group', editTitle: 'Editing: {name}', save: 'Save changes', edit: 'Edit', deactivate: 'Deactivate group', deactivateTitle: 'Deactivate {name}?', deactivateDescription: 'The group will no longer be available for new mentions. Previous mention history will remain.', cancel: 'Cancel', visibility: 'Group type', personalOption: 'Personal group', sharedOption: 'Shared group', loading: 'Loading communication groups.', empty: 'No groups yet.', noResults: 'No employee matches this search.', denied: 'You do not have permission to view communication groups.', loadError: 'Groups could not be loaded. Check your connection and try again.', validation: 'Enter a group name before saving.', permissionError: 'You do not have permission to change this group.', networkError: 'The server could not be reached. Your form is still open; try again.', error: 'The group could not be saved. Your form is still open.', success: 'Group saved.', deactivated: 'Group deactivated.', previewMore: '+{count} more',
};

export const communicationGroupsText: Record<Locale, typeof en> = {
  en,
  ar: {
    title: 'مجموعات التواصل', personal: 'مجموعاتي', shared: 'المجموعات المشتركة', name: 'اسم المجموعة', members: 'الأعضاء', memberCount: '{count} أعضاء', search: 'ابحث عن موظف', add: 'إضافة موظف', remove: 'إزالة', create: 'إنشاء مجموعة جديدة', createTitle: 'إنشاء مجموعة', editTitle: 'تعديل المجموعة: {name}', save: 'حفظ التغييرات', edit: 'تعديل', deactivate: 'تعطيل المجموعة', deactivateTitle: 'تعطيل مجموعة {name}؟', deactivateDescription: 'لن تظهر المجموعة في عمليات الذكر الجديدة، وسيبقى سجل الذكر السابق محفوظاً.', cancel: 'إلغاء', visibility: 'نوع المجموعة', personalOption: 'مجموعة شخصية', sharedOption: 'مجموعة مشتركة', loading: 'جاري تحميل مجموعات التواصل.', empty: 'لا توجد مجموعات بعد.', noResults: 'لا يوجد موظف يطابق هذا البحث.', denied: 'ليست لديك صلاحية عرض مجموعات التواصل.', loadError: 'تعذر تحميل المجموعات. تحقق من الاتصال وحاول مرة أخرى.', validation: 'اكتب اسم المجموعة قبل الحفظ.', permissionError: 'ليست لديك صلاحية تغيير هذه المجموعة.', networkError: 'تعذر الوصول إلى الخادم. ما زال النموذج مفتوحاً؛ حاول مرة أخرى.', error: 'تعذر حفظ المجموعة. ما زال النموذج مفتوحاً.', success: 'تم حفظ المجموعة.', deactivated: 'تم تعطيل المجموعة.', previewMore: '+{count} آخرون',
  },
};
